micronaut:
  application:
    name: pixKeymanagerRest
  server:
    port: ${SERVER_PORT:8080}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEY_MANAGER_GRPC_HOST:localhost}:${KEY_MANAGER_GRPC_PORT:50051}'

jackson:
  serialization:
    writeDatesAsTimestamps: false
